baseDePreguntas = [
    {
      pregunta: `¿Como se llama este componente?`,
      imagen: `https://freepngimg.com/thumb/cpu/34053-6-cpu-cabinet-photos.png`,
      respuesta: `CPU`,
      distractores: [`Monitor`, `Mouse`, `Teclado`],
      ayuda: `Contiene dentro la placa madre`,
      ayudaImg: `https://images.pexels.com/photos/163140/technology-computer-motherboard-chips-163140.jpeg?cs=srgb&dl=pexels-pixabay-163140.jpg&fm=jpg`,
    },
    {
      pregunta: `¿Cuál es la unidad minima de informacion?`,
      respuesta: `bit`,
      distractores: [`gigabite`, `electron`, `laser`],
      ayuda: `indica encendido o apagado`,
      ayudaImg: `https://img.freepik.com/free-vector/futuristic-binary-code-numbers-digital-data-background_1017-25334.jpg?w=900&t=st=1665034128~exp=1665034728~hmac=2a7be432e527463a23e62632150de3d3ba5f6ea9f35c55caf16b2caafee1e7c6`,
    },
    {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
      {
        pregunta: `¿Es un programa de edicion de textos?`,
        imagen: `https://cdn-icons-png.flaticon.com/512/732/732226.png`,
        respuesta: `WORD`,
        distractores: [`EXCEL`, `PAINT`, `AJEDREZ`],
        ayuda: `Su traduccion al ingles es PALABRA`,
      },
  ];